[workspace]
authors = ["Damineni Hemanth Satya Veer <hemanthdamineni@gmail.com>"]
channels = ["conda-forge", "pytorch"]
name = "SynchroCity"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
numpy = ">=2.3.3,<3"
flask = ">=3.1.2,<4"
flask-cors = ">=6.0.1,<7"
watchdog = ">=6.0.0,<7"
yaml = ">=0.2.5,<0.3"
opencv = ">=4.12.0,<5"
ultralytics = ">=8.3.204,<9"
pytorch = ">=2.7.1,<3"
torchvision = ">=0.23.0,<0.24"
torchaudio = ">=2.8.0,<3"
cpuonly = ">=2.0,<3"
