algorithm: PPO
total_timesteps: 1000
learning_rate: 0.0003
n_steps: 128
batch_size: 64
gamma: 0.99
gae_lambda: 0.95
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
checkpoint_dir: C:\\Users\\heman\\Desktop\\Traffic Simulator\\models\\rl



